version: '3.8'

services:
  db:
    image: postgres:15
    container_name: deutsche-postgres
    environment:
      POSTGRES_DB: deutsche
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: priyankak3/deutsche-springboot-demo:latest
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/deutsche
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8081
      SERVER_SERVLET_CONTEXT_PATH: /api/v1
      SPRING_APPLICATION_NAME: deutsche-springboot-demo
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: 1.0
    restart: unless-stopped

volumes:
  db_data:
